### ISSUE TITLE
Encountered problems during the inference process.

### ISSUE THREAD

**Issue by sw1ngz** [LiuTingWed/CriDiff#3]
Your work is excellent, and I have received a lot of inspiration from it. At the same time, I have some questions, but I encountered difficulties during the inference process. Could you provide more detailed steps for the reasoning? Thank you! Below are the problems I encountered:

File "/home/user/zwm/CriDiff-main/infer_allCp_gpu0.py", line 252, in <module>
    main()
  File "/home/user/zwm/CriDiff-main/infer_allCp_gpu0.py", line 94, in main
    diffusion = DiffSOD(args, sampling_timesteps=args.sampling_timesteps if args.sampling_timesteps > 0 else None)
  File "/home/user/zwm/CriDiff-main/module/DiffusionModel.py", line 522, in __init__
    self.model = UnetAtt(dim=64, dim_mults=(1, 2, 4, 8), cp_condition_net = args.cp_condition_net, self_condition=args.self_condition, with_time_emb=True,
AttributeError: 'Namespace' object has no attribute 'cp_condition_net'

Then When I added the pre-trained model you provided in the config, the generated images are all black.

**Comment by LiuTingWed** [comment]
Thanks for watching. :-)

Sorry, I forget to add the variable cp_condition_net during the code refactoring. But it doesn't matter, because during the inference stage, the parameters of PVT will be loaded initially and then overwritten by the trained model's parameters.

Actually, based on my understanding, all 2D prostate data are derived from 3D data by slicing. During the slicing process, some images that are completely black represent the absence of the prostate gland. Therefore, there are some completely black data in the existing 2D prostate dataset, including training and testing sets. So, are all the images you inferenced from the test set black, or are some of them black?
![QQ截图20241223232906](https://github.com/user-attachments/assets/cdd2a3fd-6609-439a-8c1a-5ea7fce52be2)

**Comment by sw1ngz** [comment]
> Thanks for watching. :-)
> 
> Sorry, I forget to add the variable cp_condition_net during the code refactoring. But it doesn't matter, because during the inference stage, the parameters of PVT will be loaded initially and then overwritten by the trained model's parameters.
> 
> Actually, based on my understanding, all 2D prostate data are derived from 3D data by slicing. During the slicing process, some images that are completely black represent the absence of the prostate gland. Therefore, there are some completely black data in the existing 2D prostate dataset, including training and testing sets. So, are all the images you inferenced from the test set black, or are some of them black? ![QQ截图20241223232906](https://private-user-images.githubusercontent.com/43695167/398198070-cdd2a3fd-6609-439a-8c1a-5ea7fce52be2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUwMDQ0NDAsIm5iZiI6MTczNTAwNDE0MCwicGF0aCI6Ii80MzY5NTE2Ny8zOTgxOTgwNzAtY2RkMmEzZmQtNjYwOS00MzlhLThjMWEtNWVhN2ZjZTUyYmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI0VDAxMzU0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlMDE1Mjg0YjlmZDM0MjRmMzJhYjgyODRlOWFhNGVmODAzMzljOTdjYjEyMzM4Y2I3NjM3NDFjZmJkODcwYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-ALgjYJqfvaf1nSwIK49LuJtcbKtG1eG9CLD8NOesmw)

![微信图片_20241224095112](https://github.com/user-attachments/assets/5eb0006b-abf6-4f5e-966a-2776ff41257f)
My work was interrupted by my classmates, which caused me to miss part of the images. Now I see that the generation is correct. I apologize for asking a silly question, haha. Additionally, I have gone through all your code and have a preliminary understanding. As a first-year Master's student, your ideas have been very helpful to me in Diffusion medical segmentation. Appreciate it!

**Comment by sw1ngz** [comment]
12
